Added education partners
ubucon-asia/2024.ubucon.asia pull request #14
Opened 2024-07-02 07:40 UTC by devilkiller-ag

This PR adds an Education Partner section with following organizations:
- JECRC
- JIC

2024-07-02 15:07 UTC, sukso96100 commented
Do you have logo image with other colors? the background color of sponsor logo area is white. So people would be difficult to find white logos you just uploaded.

2024-07-03 11:49 UTC, sukso96100 requested changes

2024-07-03 11:49 UTC, sukso96100 commented on src/assets/education_partners/jecrc.png
Dark logo please. This won't be much visible on website's light background.

2024-07-03 11:49 UTC, sukso96100 commented on src/assets/education_partners/jic.png
Dark logo please. This won't be much visible on website's light background.

2024-07-06 23:26 UTC, devilkiller-ag commented
> Do you have logo image with other colors? the background color of sponsor logo area is white. So people would be difficult to find white logos you just uploaded.

We don't have one yet. I will request the team to get dark logos.

2024-07-19 09:29 UTC, sukso96100 commented
Seems like you guys now have dark logo?

https://x.com/UbuConAsia/status/1814227754440634671?t=6q_fzp2yeYECz1yx1yy2Xg&s=19

2024-07-22 17:33 UTC, devilkiller-ag commented
Yes, but the ones I have are blue. I have incorporated them in this PR.

2024-07-22 17:52 UTC, Aryan20 commented
@devilkiller-ag Please post a screenshot of the change as a comment.

2024-07-25 03:35 UTC, devilkiller-ag commented
> @devilkiller-ag Please post a screenshot of the change as a comment.

Here it is:
![Screenshot (495)](https://github.com/user-attachments/assets/fd446772-f369-4ef0-81e2-4fea178599ad)

2024-07-25 03:37 UTC, sukso96100 commented
Looks good to me now :) merging!

2024-07-25 03:38 UTC, merged